

export default function Services() {
  return (
    <>
    <div>
<h1>Services we offer</h1>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio cumque sit atque minima magnam cum, a fugit facilis quod ullam quas beatae eveniet ipsum accusantium culpa enim! Temporibus commodi quia ullam voluptates atque voluptatum ea molestias soluta quae, rerum magni facilis modi corporis aliquid, sit magnam dicta tenetur id mollitia blanditiis aliquam expedita fuga. Voluptatum deserunt molestiae ipsum obcaecati. Corrupti, nobis assumenda cum, iure aspernatur doloribus fugit porro eveniet distinctio quibusdam dolor quos optio adipisci ipsum quam voluptate maxime quod soluta recusandae obcaecati! Autem ipsa nesciunt consectetur nihil molestiae, quia repellendus eum dignissimos provident voluptate recusandae, expedita, voluptatem corporis illum!</p>
<br />
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam rerum dicta officiis! Error quidem qui doloremque culpa veniam molestias soluta reprehenderit ullam reiciendis consectetur. Corrupti eaque sequi, alias, nesciunt corporis repellat placeat sit adipisci recusandae voluptatibus quisquam amet repellendus explicabo iusto modi aut reprehenderit veniam quo consectetur repudiandae ratione odio facere! Hic, expedita magnam alias architecto adipisci fugit enim delectus sed error, impedit repellat magni in totam repudiandae suscipit dolores cumque quia, consectetur eos quam quo nihil. Nulla minima aliquam voluptatem veritatis? Sed non officia hic, minima eligendi ipsum saepe sapiente rerum tempore, ipsam sequi dolores rem laudantium. Laborum, rerum?</p>
<br />
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam rerum dicta officiis! Error quidem qui doloremque culpa veniam molestias soluta reprehenderit ullam reiciendis consectetur. Corrupti eaque sequi, alias, nesciunt corporis repellat placeat sit adipisci recusandae voluptatibus quisquam amet repellendus explicabo iusto modi aut reprehenderit veniam quo consectetur repudiandae ratione odio facere! Hic, expedita magnam alias architecto adipisci fugit enim delectus sed error, impedit repellat magni in totam repudiandae suscipit dolores cumque quia, consectetur eos quam quo nihil. Nulla minima aliquam voluptatem veritatis? Sed non officia hic, minima eligendi ipsum saepe sapiente rerum tempore, ipsam sequi dolores rem laudantium. Laborum, rerum?</p>

<br />
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam rerum dicta officiis! Error quidem qui doloremque culpa veniam molestias soluta reprehenderit ullam reiciendis consectetur. Corrupti eaque sequi, alias, nesciunt corporis repellat placeat sit adipisci recusandae voluptatibus quisquam amet repellendus explicabo iusto modi aut reprehenderit veniam quo consectetur repudiandae ratione odio facere! Hic, expedita magnam alias architecto adipisci fugit enim delectus sed error, impedit repellat magni in totam repudiandae suscipit dolores cumque quia, consectetur eos quam quo nihil. Nulla minima aliquam voluptatem veritatis? Sed non officia hic, minima eligendi ipsum saepe sapiente rerum tempore, ipsam sequi dolores rem laudantium. Laborum, rerum?</p>
<br />
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam rerum dicta officiis! Error quidem qui doloremque culpa veniam molestias soluta reprehenderit ullam reiciendis consectetur. Corrupti eaque sequi, alias, nesciunt corporis repellat placeat sit adipisci recusandae voluptatibus quisquam amet repellendus explicabo iusto modi aut reprehenderit veniam quo consectetur repudiandae ratione odio facere! Hic, expedita magnam alias architecto adipisci fugit enim delectus sed error, impedit repellat magni in totam repudiandae suscipit dolores cumque quia, consectetur eos quam quo nihil. Nulla minima aliquam voluptatem veritatis? Sed non officia hic, minima eligendi ipsum saepe sapiente rerum tempore, ipsam sequi dolores rem laudantium. Laborum, rerum?</p>
<br />
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam rerum dicta officiis! Error quidem qui doloremque culpa veniam molestias soluta reprehenderit ullam reiciendis consectetur. Corrupti eaque sequi, alias, nesciunt corporis repellat placeat sit adipisci recusandae voluptatibus quisquam amet repellendus explicabo iusto modi aut reprehenderit veniam quo consectetur repudiandae ratione odio facere! Hic, expedita magnam alias architecto adipisci fugit enim delectus sed error, impedit repellat magni in totam repudiandae suscipit dolores cumque quia, consectetur eos quam quo nihil. Nulla minima aliquam voluptatem veritatis? Sed non officia hic, minima eligendi ipsum saepe sapiente rerum tempore, ipsam sequi dolores rem laudantium. Laborum, rerum?</p>
<br />
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam rerum dicta officiis! Error quidem qui doloremque culpa veniam molestias soluta reprehenderit ullam reiciendis consectetur. Corrupti eaque sequi, alias, nesciunt corporis repellat placeat sit adipisci recusandae voluptatibus quisquam amet repellendus explicabo iusto modi aut reprehenderit veniam quo consectetur repudiandae ratione odio facere! Hic, expedita magnam alias architecto adipisci fugit enim delectus sed error, impedit repellat magni in totam repudiandae suscipit dolores cumque quia, consectetur eos quam quo nihil. Nulla minima aliquam voluptatem veritatis? Sed non officia hic, minima eligendi ipsum saepe sapiente rerum tempore, ipsam sequi dolores rem laudantium. Laborum, rerum?</p>
<br />
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam rerum dicta officiis! Error quidem qui doloremque culpa veniam molestias soluta reprehenderit ullam reiciendis consectetur. Corrupti eaque sequi, alias, nesciunt corporis repellat placeat sit adipisci recusandae voluptatibus quisquam amet repellendus explicabo iusto modi aut reprehenderit veniam quo consectetur repudiandae ratione odio facere! Hic, expedita magnam alias architecto adipisci fugit enim delectus sed error, impedit repellat magni in totam repudiandae suscipit dolores cumque quia, consectetur eos quam quo nihil. Nulla minima aliquam voluptatem veritatis? Sed non officia hic, minima eligendi ipsum saepe sapiente rerum tempore, ipsam sequi dolores rem laudantium. Laborum, rerum?</p>

    
    
    </div>
    </>
    
  )
}
